---
- hosts: all
  become: true

  vars:
    test_var: 'this came from Ansible!'

  tasks:
    - name: gather ec2 facts
      action: ec2_metadata_facts
      when: "'amazon' in ansible_bios_version"

    - name: template test
      template:
        src: templates/test.j2
        dest: /tmp/template_test
        owner: centos
        group: centos
        mode: 0644

    - name: Ansible register variable basic example
      shell: curl -4 ifconfig.co
      register: output

    - debug:
      var: output.stdout
